BidOneCodingTest/Models/ErrorViewModel.cs
using System;

namespace BidOneCodingTest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BidOneCodingTest/Models/NameModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BidOneCodingTest.Models
{
    public class NameModel
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
    }
}

BidOneCodingTest/Models/ReadAndWriteJsonFile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;

namespace BidOneCodingTest.Models
{
    public class ReadAndWriteJsonFile
    {
        public ReadAndWriteJsonFile() { }
        public string Read(string fileName, string location)
        {
            string root = "wwwroot";
            var path = Path.Combine(Directory.GetCurrentDirectory(),
                root,
                location,
                fileName
                );
            string jsonResult;
            using (StreamReader streamReader = new StreamReader(path))
            {
                //Read whole json file data
                jsonResult = streamReader.ReadToEnd();
            }
            return jsonResult;
        }

        public void Write(string fileName, string location, string jSONString)
        {
            string root = "wwwroot";
            var path = Path.Combine(
            Directory.GetCurrentDirectory(),
            root,//root is "wwwroot" folder
            location,//location of folder data where Names.json file is there
            fileName);//filename is Names.json

            using (var streamWriter = File.CreateText(path))
            {
                //write the new data into Names.json file
                streamWriter.Write(jSONString);
            }
        }
    }
}

BidOneCodingTest/Controllers/HomeController.cs
using BidOneCodingTest.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BidOneCodingTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BidOneCodingTest/Controllers/NamesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BidOneCodingTest.Models;
using Newtonsoft.Json;

namespace BidOneCodingTest.Controllers
{
    public class NamesController : Controller
    {
        List<NameModel> names = new List<NameModel>();
        //ReadAndWriteJsonFile holds the logic to extract the data from json file and also it has logic to update the data
        ReadAndWriteJsonFile readWrite = new ReadAndWriteJsonFile();
        public IActionResult Index()
        {
            //Deserializes json data into .net object
            names = JsonConvert.DeserializeObject<List<NameModel>>(readWrite.Read("Names.json", "data"));
            //send the object to view to display data from json file
            return View(names);
        }

        [HttpPost]
        public IActionResult AddName(NameModel nameModel)
        {
            //Deserializes json data into .net object
            names = JsonConvert.DeserializeObject<List<NameModel>>(readWrite.Read("Names.json", "data"));
            //assign the new id to add new records
            nameModel.id = names.Count + 1;
            NameModel name = names.FirstOrDefault(x => x.id == nameModel.id);
            if (name == null)
            {
                //add new records into the existing deserialised object "names"
                names.Add(nameModel);
            }
            else
            {
                int index = names.FindIndex(x => x.id == nameModel.id);
                names[index] = nameModel;
            }
            //Serialise the updated object data
            string jSONString = JsonConvert.SerializeObject(names);
            //send the data to ReadAndWriteJsonFile class which is based in "Models" folder
            readWrite.Write("Names.json", "data", jSONString);
            return this.Ok("Data is saved successfully!");
        }

    }
}

BidOneCodingTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BidOneCodingTest/Views/Names/Index.cshtml
@model List<BidOneCodingTest.Models.NameModel>
<!DOCTYPE html>
<html>
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js">
    </script>
</head>
<body>
    <form>
        <fieldset>
            <div>
                <label for="firstName">First Name</label>
                <input type="text" name="firstName" id="firstName" placeholder="Enter your first name" />
            </div>
            <div>
                <label for="lastName">Last Name</label>
                <input type="text" name="lastName" id="lastName" placeholder="Enter your last name" />
            </div>
            <div>
                <input type="button" value="submit" class="submit" onclick="return saveData()" />
            </div>
        </fieldset>
    </form>
    <br />
    <table border="1">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.firstName</td>
                <td>@item.lastName</td>
            </tr>

        }
    </table>
</body>
</html>

<script>
    function saveData() {
        var firstName = document.getElementById("firstName").value;
        var lastName = document.getElementById("lastName").value;
        if (firstName !== "" && lastName !== "") {
            $.ajax({
                type: "POST",
                url: "@Url.Action("AddName","Names")",
                data: {
                    firstName: firstName,
                    lastName: lastName
                },
                // dataType: "application/json; charset=utf-8",
                success: function (response) {
                    alert(response)
                    window.location.reload();
                }
            });
        }
        else {
            alert("Please enter all fields");
            window.location.reload();
        }

    }
</script>

BidOneCodingTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BidOneCodingTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Names" asp-action="Index">BidOneCodingTest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BidOneCodingTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>